on:
    push:
        branches:
            - main
            - release/*

jobs:
    build:
        name: Build XCFramewoek
        runs-on: macos-26

        steps:
            - uses: actions/checkout@v4
            - name: Install brew tools
              run: |
                  brew install autoconf automake libtool pkg-config
            - name: Build XCFramework
              run: |
                  ./autogen.sh
                  cd IDE/apple-universal
                  ./build-wolfssl-framework.sh
