on:
    push:
        branches:
            - main
            - release/*

jobs:
    build:
        name: Build XCFramework
        runs-on: macos-26

        steps:
            - uses: actions/checkout@v4
            - name: Install brew tools
              run: |
                  brew install autoconf automake libtool pkg-config
            - name: Autogen
              run: ./autogen.sh

            - name: Build WolfSSL XCFarmework
              run: |
                  cd IDE/apple-universal
                  ./build-wolfssl-framework.sh

            - name: Compress framwork file
              run: |
                  zip -r IDE/apple-universal/artifacts/xcframework/libwolfssl.xcframework.zip IDE/apple-universal/artifacts/xcframework/libwolfssl.xcframework

            - name: Archive framework archive
              uses: actions/upload-artifact@v4
              with:
                  name: zipped-framework
                  path: |
                      IDE/apple-universal/artifacts/xcframework/libwolfssl.xcframework.zip
