on:
    push:
        branches:
            - main
            - release/*

jobs:
    build:
        name: Build XCFramewoek
        runs-on: macos-26

        steps:
            - uses: actions/checkout@v4
            - name: Install brew tools
              run: |
                  brew install autoconf automake libtool pkg-config
